name: Release
on: workflow_dispatch

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  release:
    runs-on: ubuntu-latest
    needs:
      - ci

    env:
      VERSION: ${{ needs.ci.outputs.version }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - uses: actions/download-artifact@v3
        with:
          name: fourmolu-binary-ubuntu-latest
          path: ./bin/
      - uses: actions/download-artifact@v3
        with:
          name: fourmolu-binary-macos-latest
          path: ./bin/
      - uses: actions/download-artifact@v3
        with:
          name: fourmolu-sdist
          path: ./sdist/

      - name: Load Hackage token secret name
        id: hackage_token_secret
        run: |
          USERNAME="$(echo "${GITHUB_ACTOR}" | tr '[:lower:]' '[:upper:]' | tr '-' '_')"
          echo "name=HACKAGE_TOKEN_${USERNAME}" >> "${GITHUB_OUTPUT}"

      - uses: brandonchinn178/haskell-actions/hackage-upload@hackage-upload
        with:
          archive: sdist/fourmolu-*.tar.gz
          token: ${{ secrets[steps.hackage_token_secret.outputs.name] }}

      - name: Make release
        run: scripts/make-release.sh
        env:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ env.VERSION }}
          bindir: ./bin/
          sdistdir: ./sdist/
